# Generated by Django 2.0.6 on 2018-10-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='date_created',
            field=models.IntegerField(),
        ),
    ]
